### ISSUE TITLE
Document the standard

### ISSUE THREAD

**Issue by dnet** [gioblu/PJON#12]
I see that the source code has plenty of comments, but a specification be much more readable in a separate Markdown file or (GitHub) wiki page.

(continued from https://news.ycombinator.com/item?id=10283322)

**Comment by gioblu** [comment]
Hi, thank you for opening this issue. I started working on the PJON wiki, please, consider it as a "public draft" with a lot of work in progress. Do you have some suggestion on how to structurize this wiki, if you think is necessary to divide it in pages and if you like ascii schematics or you would prefer images??

Thanks you again

**Comment by dnet** [comment]
Thanks, it looks nice. I'm good with ASCII art, and will take a more detailed look at it soon.

**Comment by gioblu** [comment]
Ciao dnet What do you think of the actual state of development (early) of the wiki?
https://github.com/gioblu/PJON/wiki

You perceive it easy to understand?
You think I missed something or the format is not coherent with a standard reference?

**Comment by dnet** [comment]
Looks good!

**Comment by gioblu** [comment]
Hi dnet, now that the standard is documented, why don't you close the issue? Or you think documentation has some downsides?
