### ISSUE TITLE
Receiver-example for RaspberryPi? (noob question)

### ISSUE THREAD

**Issue by PhinPhin** [gioblu/PJON#134]
Hi,

I'm working on a project that needs to connect 2 Arduinos to a Raspberry Pi 3. The example only features the Pi transmitting data, how can I actually send periodically requests to the Arduinos to send their data after another? Or can I use the Arduino-examples on the Pi?

**Comment by gioblu** [comment]
Ciao @PhinPhin I will be back operational tomorrow, and add the example you report missing, in the meantime you can edit examples dedicated to arduino and test them on RPI adding the necessary constants toy can see in the Rpi transmitter example

**Comment by PhinPhin** [comment]
That's cool, thanks :) I'm sure that will help other people who're not so much into programming, too

**Comment by gioblu** [comment]
Ciao @PhinPhin here you find the example you have requested: https://github.com/gioblu/PJON/tree/master/examples/RPI/Local/ThroughSerial/BlinkTestReceiver

I hope will be useful for you and other users, sorry for being a little late :)
