### ISSUE TITLE
Routing protocol support?

### ISSUE THREAD

**Issue by Matheus-Garbelini** [gioblu/PJON#140]
Hello, I'm seeing that pjon is growing more and more. And with IOT getting very hot nowadays, are there plannings in implementing a routing protocol to use pjon in LoRa or similar radio modules? (Right now making some tests with a LoRa strategy). I've seen that you have an over sampling strategy to use in simple radio transceiver, but it would be nice if could be possible to create a mesh or tree based routing strategy?

If so, i would recommend implementing a RPL like routing protocol (from 6lowpan). Thanks

**Comment by gioblu** [comment]
Ciao @Matheus-Garbelini yes, after the release of v9 we can start reasoning about this feature.
I think this routing / mesh networking entity should be built on top of the PJON class, having its own specification and should not be a strategy, generally strategies are used to implement a certain data link, so layer 2, PJON acts as layer 3 (or network layer). The newcoming layer should be transport, containing the routing and segmentation features. So I would suggest you, if you are testing LoRa, to implement a basic data link strategy supporting framing. With that it will be possible through PJON to build a mesh network implementing and specifying layer 3.

**Comment by gioblu** [comment]
Ciao @Matheus-Garbelini how its going? Would you share your experiments with the LoRa strategy? I bought some LoRa modules, it would be nice to implement it in the next version.

Speaking instead about routing, I was considering an additional abstraction for the routing process, to support different options, because a single routing strategy would in any case not cover all the use cases. What do you think about it?

**Comment by Matheus-Garbelini** [comment]
@gioblu Hello, gioblu, thanks for tour interest, I actually used a third party arduino library when wrapping PJON, is it okay to joing another library to pjon or it needs to be a clean implementation?

**Comment by gioblu** [comment]
The only problem I can see could be about the license compatibility. A third party library could be included within the strategy, no problem. Another thing to consider is the library compatibility.

**Comment by Matheus-Garbelini** [comment]
As I didnt create a repository yet, here's the initial files that reside in strategies folder (2 files and 2 examples)

ThroughLora.h: https://pastebin.com/nbTGzHv1
Timing.h: https://pastebin.com/hp42Ubds
Client Example: https://pastebin.com/TDpWbagA
Server Example: https://pastebin.com/3GDJmUjf
Third Party Lora Library that i used in startegy (LoRa.h): https://github.com/sandeepmistry/arduino-LoRa

My code that wraps the reading method is not optmized yet, maybe you will find sumething weird there.
Also, I didn't made a static method to access special funcitons of lora, of wich i should put inside strategy.

**Comment by Matheus-Garbelini** [comment]
@gioblu Next week i will return to focus in this research of mine so i can work all day with this.
The generic routing layer is grat idea, i'd love that. None of the current iot OS implementations allow that, so it would be a great breakthrough in this.

**Comment by gioblu** [comment]
The code seems quite ok! It would be nice to receive a pr from you to record your contribution.
I am now not able to test it practically so I would make some cleanup from your pr but not go much into it being not able to verify its state after my changes are done.

About the routing, I would develop this abstraction level as originally planned within [OSPREY](https://github.com/gioblu/OSPREY) where there are already some early experiments. 

It would be probably sane and nice to create a tree based routing (that is really simple) as a first step, on top of a generalized prototype that can be feeded in OSPREY like strategies are feeded to PJON. 

Then this OSPREY entity will receive PJON instances passed by user and route packets within this instances (so transport a packet from a medium to the other) and also outwards to other users (transport a packet through the network from one device to another).

**Comment by Matheus-Garbelini** [comment]
@gioblu a tree based routing is perfect for LoRa application. I had looked into OSPREY and it looks very solid even at this stage.
This weekend i will submit the PR so you can review it better.
About the third party library, it uses MIT license, so I think it will can be included alongside a LoRa strategy with no problem.
I will get back to you soon, and thank you so much for your work, i've been following your work since the very first versions.

**Comment by gioblu** [comment]
Thank you @Matheus-Garbelini for your passion and support to the project :).
OSPREY is actually not working it is a place where I was sketching experimentally, it should be already done but I didnt have the physical time for that too :)

**Comment by gioblu** [comment]
@Matheus-Garbelini speaking about third-party libraries, they should not be included in the repository but only linked in as we did in the other strategies. Thank you again!

**Comment by gioblu** [comment]
CIao @Matheus-Garbelini finally port identification arrived. Now as it is done in TCP different encapsulated protocols can be identified dynamically. This is extremely useful for encapsulating the routing protocol we were speaking about.

**Comment by Matheus-Garbelini** [comment]
@gioblu Hello again in this new year :). I made an PR so you can review better the changes.
The documentation of the strategy is not yet made.
So LoRa RAW communication with PJON is made with this changes but the next steps will be applied directly to OSPREY?

**Comment by gioblu** [comment]
Ciao @Matheus-Garbelini I have studied your proposal, it seems really well done (see related pr).
Yes, for routing the next step is to make OSPREY work basically supporting the PJON instances, define a port identification for it, and start the routing implementation : )

**Comment by Matheus-Garbelini** [comment]
@gioblu Hello, sorry for the delay. I tested the last changes and everything seems OK, next weekend I can prepare the network examples and strategy documentation if you'd like.
Also, I finished the Sensor/Gateway node project (For Lora and/or XBEE). And as an option of cost, the MCU of choice will be STM32f103C8T6 (1 dollar each in lcsc.com). The total cost of the project including GPS/BDS is around 20 dollars per board. I'm waiting for the approval of my coordinator to buy the components.

Here's the initial rendering of the board and the mounting in raspberry pi (for gateway nodes):
![foto4](https://user-images.githubusercontent.com/6465668/34700994-ece723ee-f4cc-11e7-88fe-8227f9737396.png)
![foto3](https://user-images.githubusercontent.com/6465668/34700997-ee578ba6-f4cc-11e7-88fe-b3893a3c1b3f.png)
![foto1](https://user-images.githubusercontent.com/6465668/34700998-f0795036-f4cc-11e7-83d7-f88c3ec368dc.png)

**Comment by gioblu** [comment]
Ciao @Matheus-Garbelini! That is a masterpiece! Really nicely done.
Is there a way to have a chat with you to define the routing protocol you would need for this?

**Comment by Matheus-Garbelini** [comment]
@gioblu Thanks for appreciating the board. I didn't use Gitter before but I just created an account there and sent you a message 👍

**Comment by ristomatti** [comment]
This looks awesome! @gioblu / @Matheus-Garbelini have you looked at the worked done for NRF24L01+ transceivers by the RF24/RFNetwork/RF24Mesh/RF24Ethernet devs? It seems to have a lot of similarities with the ideas you've been discussing.

**Comment by gioblu** [comment]
Ciao @ristomatti @Matheus-Garbelini we are discussing here: https://github.com/gioblu/PJON/issues/167 about basic routing functionality. The change proposed by @fredilarsen of adding a constructor to PJON to also support strategies virtual inheritance seems really cool. This change could help to reduce the amount of complication needed by the routing protocol layer, supporting arrays of PJON instances with different strategies that can be used dynamically.
If you are interested to help defining this part feel free to share your point of view!
Thank you for your support.

**Comment by ristomatti** [comment]
@gioblu Thanks but I doubt I'd have anything to contribute on that. Just wanted to point out the RF24 project in case some ideas could come up from the work done there. :)

**Comment by gioblu** [comment]
Ciao, I will close here for now because we finally have added an initial transparent routing implementation.
