### ISSUE TITLE
'byte': redefinition; different basic types

### ISSUE THREAD

**Issue by gonnavis** [gioblu/PJON#151]
Run the WINX86/Local/ThroughSerial/BlinkTest demo, error say "'byte': redefinition; different basic types", and find it already defined in rpcndr.h "typedef unsigned char byte;"

**Comment by gioblu** [comment]
Ciao @gonnavis thank you for the report. Looking in!

**Comment by gioblu** [comment]
CIao @gonnavis is this change:

```
  #ifndef byte
    typedef char byte;
  #endif
```

 at line 28 of PJON_WINX86_Interface.h fixing the issue? 
(Cannot test in this moment)

**Comment by gioblu** [comment]
Ciao @gonnavis the linked commit should solve the issue :)
