### ISSUE TITLE
EthernetUdp.h vs EthernetUDP.h

### ISSUE THREAD

**Issue by ibantxo** [gioblu/PJON#153]
Arduino/libraries/PJON/interfaces/ARDUINO/UDPHelper_ARDUINO.h:9:27: fatal error: EthernetUDP.h: No such file or directory
   #include <EthernetUDP.h>

That file that is in Arduino/libraries/Ethernet/src folder is EthernetUdp.h

**Comment by gioblu** [comment]
Ciao @ibantxo thank you for reporting this inconsistency, soon the fix 👍

**Comment by gioblu** [comment]
Ciao @ibantxo thank you again for the report. Fixed in master.
