### ISSUE TITLE
Request for well-known port for the ModuleInterface protocol

### ISSUE THREAD

**Issue by fredilarsen** [gioblu/PJON#154]
As a protocol running on top of PJON, having a standard port number is advantageous to keep the traffic isolated from other protocols and non-protocol-specific packets.

I am hereby requesting the ModuleInterface protocol to be put on the well-known protocols list and be assigned a standard port number, for example 100.

A pull request for the PJON-known-protocols-list.md is sent.

Fred Larsen

**Comment by gioblu** [comment]
Ciao @fredilarsen request accepted :) soon pull request merge will follow!
Thank you for your support and compliments for the huge work done on [ModuleInterface](https://github.com/fredilarsen/ModuleInterface)
