### ISSUE TITLE
¿Used with RF link?

### ISSUE THREAD

**Issue by domonetic** [gioblu/PJON#16]
¿utilizable con link RF?
I can use it with a single RF module or only cable?
You can comment more about of medium of transportation?

**Comment by gioblu** [comment]
Hi there, if you take a close look to the readme you can find the link to the 315/433Mhz implementation of PJON: https://github.com/gioblu/PJON_ASK

Thank you for your suggestion. I will bring more clear this information.

**Comment by domonetic** [comment]
Thank you very much, the library is very useful.
Sometimes we do not know how to connect a network type 1wire whats hardware use.

**Comment by gioblu** [comment]
Hi domo, why don't you close this issue?
