### ISSUE TITLE
ATmega1284P compatibility

### ISSUE THREAD

**Issue by fabpolli** [gioblu/PJON#168]
Hi, I've tried to use Your library with the MCU ATmega1284P but without success. Some errors appear during compile time of sketch in Arduino's IDE. Do You have a plan to make suitable Your library with that MCU?
I report some error displayed from compiler:
error: 'PJON_IO_PIN_TO_PORT_REG' was not declared in this scope
error: 'PJON_IO_PIN_TO_BIT' was not declared in this scope

**Comment by gioblu** [comment]
Ciao @fabpolli ATmega1284P IO macros are not present, for that reason you get this error.
Are you trying to get SoftwareBitBang strategy? I dont have here now a ATmega1284P to try with. 
But if you want to try to port it, it is not that difficult, see how ATtiny85 IO macros are defined here: https://github.com/gioblu/PJON/blob/master/interfaces/ARDUINO/PJON_IO.h#L172 
You have only to define the macros for ATmega1284P, defined only if the ATmega1284P related constant is defined, to point to the correct reg and pin number. Feel free to ask for support if needed.
Happy tinkering.

**Comment by fabpolli** [comment]
Hi, I've added this code into PJON_IO.h:
/* AVR ATMEGA1284P -------------------------------------------------------- */

#if defined(__AVR_ATmega1284P__)
  #define PJON_IO_PIN_TO_PORT_REG(P) \
    ((P >= 9 && P <= 16) ? &PORTD : ((P >= 19 && P <= 26) ? &PORTC : ( ( (P >=1 && P <=3) || (P >= 40 && P <= 44) ) ? &PORTB : &PORTA) ))
  #define PJON_IO_PIN_TO_DDR_REG(P) \
    ((P >= 9 && P <= 16) ? &DDRD : ((P >= 19 && P <= 26) ? &DDRC : ( ( (P >=1 && P <=3) || (P >= 40 && P <= 44) ) ? &DDRB : &DDRA) ))
  #define PJON_IO_PIN_TO_PIN_REG(P) \
    ((P >= 9 && P <= 16) ? &PIND : ((P >= 19 && P <= 26) ? &PINC : ( ( (P >=1 && P <=3) || (P >= 40 && P <= 44) ) ? &PINB : &PINA) ))
  #ifndef PJON_IO_PIN_TO_BIT
    #define PJON_IO_PIN_TO_BIT(P) \
      ((P >= 0 && P <= 7) ? P : ((P >= 8 && P <= 13) ? P - 8 : P - 14))
  #endif

  #define PJON_IO_PIN_TO_TIMER(P) \
    ((P == 6 || P == 5) ? &TCCR0A : ((P == 9 || P == 10) ? \
    &TCCR1A : ((P == 11 || P == 3) ? &TCCR2A : 0)))
  #define PJON_IO_PIN_TO_TIMER_BIT(P) \
    ((P == 6) ? COM0A1 : ((P == 5) ? COM0B1 : ((P == 9) ? \
    COM1A1 : ((P == 10) ? COM1B1 : ((P == 11) ? COM2A1 : COM2B1)))))
#endif

I've some problem regarding PJON_IO_PIN_TOBIT and PJON_IO_PIN_TO_TIMER because I can't undertand the link between IO pin and bit, can You explain me how and when Your library use IO_PIN_TOBIT?
PIN_TO_TIMER: I'm trying to find timer's documentation in datasheet but without success for now, 714 pages are too much for me to find this information quickly :-)

**Comment by gioblu** [comment]
Ciao @fabpolli sorry for the delay in the answer,  `IO_PIN_TO_BIT` is used in `PJON_IO_ATOMIC_WRITE`, through arduino `bitwrite` function sets the value of a certain bit in the register, at line https://github.com/gioblu/PJON/blob/master/interfaces/ARDUINO/PJON_IO.h#L303
you can see `PJON_IO_PIN_TO_PORT_REG` returning the correct register, then simply the bit in the register corresponding to the pin number is set as or read as requested. 

What exactly is not clear, how can I help you?

**Comment by gioblu** [comment]
Ciao @fabpolli see https://www.arduino.cc/en/Reference/PortManipulation

**Comment by fabpolli** [comment]
Ciao @gioblu PJON_IO_PIN_TO_BIT fixed but I've some problem to understand the link between PJON_IO_PIN_TO_TIMER and pin. I've tried to follow Atmega328 configuration and it's own datasheet but without success.
TCCR0A, TCCR1A, etc.; COM0A1, COM0B1, etc.. are used for pwm pins? In PJON how they are used? I'm sorry for noob questions ;-)

**Comment by gioblu** [comment]
Ciao @fabpolli, PWM feature is not used directly by PJON, although PWM pins can be selected to be used as normal digital IO for PJON communication, for that reason access and control to PWM pins is implemented, not to limit the pin choice to users who may need.

I will give a deep look to the 1284P DS.
Thank you for your support @fabpolli

**Comment by fabpolli** [comment]
@gioblu This Monday I will post here the last version of my work ,I left the file it at work :-( . I correctly set PJON_IO_PIN_TO_PORT_REG and PJON_IO_PIN_TO_BIT but my skill are not enougth to set PJON_IO_PIN_TO_TIMER

**Comment by gioblu** [comment]
Ciao @fabpolli you are right `PJON_IO_PIN_TO_TIMER` is not used by PJON codebase, they are remains of the old digitalWriteFast library we started from. If you have already finished port red and pin to bit, it should all be ready for testing! 

It may work with default timing, although timing constats may need some tweaking for optimal performance (see Timing.h); https://github.com/gioblu/PJON/blob/master/strategies/SoftwareBitBang/Timing.h#L72

Il will remove the useless `PJON_IO_PIN_TO_TIMER` and relate the commit to this issue.
Thank you for your support.

**Comment by fabpolli** [comment]
Ok, I will make some tests this evening and if the communication between mcu will be fine with all pins I will commit my work

**Comment by gioblu** [comment]
Ciao @fabpolli any help needed? (It may not work on all pins with the same performance depending on the hardware used)

**Comment by fabpolli** [comment]
I've made some tests and it seem to work perfectly with softwareserial and with serial1 too for example. I can't commit on github due to permissions. I put heare the code added to PJON_IO.h of arduino
/* AVR ATMEGA1284P -------------------------------------------------------- */

#if defined(__AVR_ATmega1284P__)
  #define PJON_IO_PIN_TO_PORT_REG(P) \
    ((P >= 9 && P <= 16) ? &PORTD : ((P >= 19 && P <= 26) ? &PORTC : ( ( (P >=1 && P <=3) || (P >= 40 && P <= 44) ) ? &PORTB : &PORTA) ))
  #define PJON_IO_PIN_TO_DDR_REG(P) \
    ((P >= 9 && P <= 16) ? &DDRD : ((P >= 19 && P <= 26) ? &DDRC : ( ( (P >=1 && P <=3) || (P >= 40 && P <= 44) ) ? &DDRB : &DDRA) ))
  #define PJON_IO_PIN_TO_PIN_REG(P) \
    ((P >= 9 && P <= 16) ? &PIND : ((P >= 19 && P <= 26) ? &PINC : ( ( (P >=1 && P <=3) || (P >= 40 && P <= 44) ) ? &PINB : &PINA) ))
  #ifndef PJON_IO_PIN_TO_BIT
    #define PJON_IO_PIN_TO_BIT(P) \
      ( (P >= 30 && P <= 37) ? ((P-37)*-1) : ( ( (P >= 1 && P <=3) || (P >=40 && P <=44) ) ? ( ( P >= 1 && P <=3 ) ? P + 5 : P - 40 ) : ( ( P >= 19 &&  P <= 26) ? P - 19 : P - 9 ) ) )
  #endif
#endif

**Comment by gioblu** [comment]
Ciao @fabpolli why don't you make a pull-request? That would record your contribution.
If that is not feasible for you I will make the addition for you and add you to the contributors list.

Have you tried SoftwareBitBang? Because the pin handling you worked on is mostly necessary to handle SoftwareBitBang single wire communication.
