### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tipsy-gypsy** [gioblu/PJON#17]
Hi,

Sorry if an issue isn't the best way to ask this, but I couldn't find any other way. Could you please specify a licence. I would really love to use this in my garage-scale (hopefully) commercial product.

**Comment by gioblu** [comment]
Hi there, you are right, the license was not complete, thank you for your report and support :). 

I added what I think is necessary:
https://github.com/gioblu/PJON/blob/master/PJON.cpp#L16
https://github.com/gioblu/PJON/blob/master/PJON.h#L21
you can find the same in the readme.

When you consider this issue solve, please close it, so we will mantain order :).
Thank you again for your support and good luck for your product development.

Gio.
