### ISSUE TITLE
MultiByte char instead unicode in Visual Studio community 2017

### ISSUE THREAD

**Issue by sigmaeo** [gioblu/PJON#173]
I just started with pjon and compiled the example "ThroughSerial\BlinkTest\Transmitter.cpp" on windows 7 with VS C++ community 2017.
First I have to change project settings to "multibyte" charset instead "unicode". Maybe this can be added to README.md?
Second I have to change the line 38 in Serial.cpp from CreateFile() to CreateFileW().
With this it compiles and work fine.

**Comment by gioblu** [comment]
Ciao @sigmaeo thank you for reporting.
Will test and fix the issue as soon as possible.

**Comment by gioblu** [comment]
Ciao @sigmaeo thank you for reporting the broken example, I have fixed as you suggested.
I have also added the vcxproj files and updated the readme to reduce the amount of steps required to have the example running. Thank you again for your support to the project.
