### ISSUE TITLE
tryting to send a 6 digit decimal no using hc12 but receiving only 2 no after decimal point 

### ISSUE THREAD

**Issue by tusharchatur01** [gioblu/PJON#181]
I am trying to send a float no with 6 digits after decimal point but in the receiver, i am getting only 2 digits after decimal point and rest are zeros how to fix this can anyone help.

**Comment by gioblu** [comment]
CIao @tusharchatur01 could you please paste here the code you are using?

**Comment by tusharchatur01** [comment]
Problem got solved used hc12. println(x, 6); getting all 6 digits transmitted
