### ISSUE TITLE
ThroughSerial RS485 usage

### ISSUE THREAD

**Issue by ovedmo** [gioblu/PJON#201]
Hi @gioblu 
with SoftwareBitBang i send all data through one line it work very good, Now what way can i connect many slaves and one master when want to try ThroughSerial strategie with 2 pins... (rs-485 ?)

**Comment by gioblu** [comment]
ciao @ovedmo take a look at this example: https://github.com/gioblu/PJON/tree/master/examples/ARDUINO/Local/ThroughSerial/RS485-Blink

it simply demonstrates how to use TS along with RS485.

**Comment by gioblu** [comment]
@ovedmo thank you for your testing feedback, always appreciated :)
Thank you again for your support!

**Comment by gioblu** [comment]
Ciao @ovedmo take a look to this schematic:
![test789](https://user-images.githubusercontent.com/764497/39434707-9e46774c-4c99-11e8-9ecc-6aa57e5a20ec.jpg)

Obviously the USB to RS485 converter could be an arduino. As you can see the enable pins are connected together. Use the setter below to tell to PJON which pin is used for the enable:
``cpp`
bus.strategy.set_enable_RS485_pin(11);
```

If separate enable setters are needed use:
```cpp
// Set RS485 reception enable pin
bus.strategy.set_RS485_rxe_pin(11);
// Set RS485 transmission enable pin
bus.strategy.set_RS485_txe_pin(12);
```

**Comment by drawkula** [comment]
Are terminating resistors optional?
Probably that does not really matter on low length busses with only few clients.

**Comment by gioblu** [comment]
What I am aware of is that termination are not needed If the latency is less than one bit duration, so required only in really extended setups with fast communication speed.

**Comment by gioblu** [comment]
Ciao @ovedmo closing here for now, feel free to reopen if required.

**Comment by ovedmo** [comment]
if i want to use bare max485 for the ThroughSerial how do i connect it...
