### ISSUE TITLE
PJON unreliable between ESP and Arduino Nano

### ISSUE THREAD

**Issue by skorokithakis** [gioblu/PJON#218]
Hello,
I just found PJON and it looks perfect for what I want to do, communication between an ESP8266 and an Arduino Nano. However, trying the "LED blink" example, I get a "blink" on the Arduino around once every second, and around ten seconds later the devices disconnect with "Connection lost".

This is a very simple circuit of one wire, so I don't know if PJON is this unreliable or if I'm doing something wrong. Is there something I can fix?

**Comment by gioblu** [comment]
Ciao @skorokithakis it should not happen. Are you testing using master?

**Comment by gioblu** [comment]
Be sure you have pulled from master https://github.com/gioblu/PJON/commit/a5563b58748885d638058f15b9640044d6c6d894

Feel free to contact me on gitter if some support is required.
Thank you again.

**Comment by skorokithakis** [comment]
I'm not sure, I'm using PlatformIO, so I think yes. I will try again and tell you more on Gitter, thanks!

**Comment by gioblu** [comment]
Ciao @skorokithakis will be a pleasure to help, sorry for the late answer.

**Comment by gioblu** [comment]
Ciao @skorokithakis as we discussed on gitter, I close here being this issue produced by using v11.0.
The issue has already been fixed with this commit: https://github.com/gioblu/PJON/commit/a5563b58748885d638058f15b9640044d6c6d894

This will be released soon in v11.1
Thank you very much for your support.

**Comment by skorokithakis** [comment]
Thank you!
