### ISSUE TITLE
How to get working with ATTiny85?

### ISSUE THREAD

**Issue by Earlz** [gioblu/PJON#23]
I'm trying to get this working with an ATTiny85 and having problems with the Arduino IDE. I installed the ATTiny package for the Arduino IDE, but get these compiler errors:

<pre>

Build options changed, rebuilding all
In file included from C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.h:33:0,

                 from C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:23:

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp: In member function 'boolean PJON::can_start()':

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:92:28: error: 'DDRD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &DDRD : (((P) >= 8 && (P) <= 13) ? &DDRB : &DDRC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:144:88: note: in expansion of macro 'digitalPinToDDRReg'

 do {if (__builtin_constant_p(P) && __builtin_constant_p(V)) __atomicWrite__((uint8_t*) digitalPinToDDRReg(P),P,V) \

                                                                                        ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:82:3: note: in expansion of macro 'pinModeFast'

   pinModeFast(_input_pin, INPUT);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:92:71: error: 'DDRC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &DDRD : (((P) >= 8 && (P) <= 13) ? &DDRB : &DDRC))

                                                                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:144:88: note: in expansion of macro 'digitalPinToDDRReg'

 do {if (__builtin_constant_p(P) && __builtin_constant_p(V)) __atomicWrite__((uint8_t*) digitalPinToDDRReg(P),P,V) \

                                                                                        ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:82:3: note: in expansion of macro 'pinModeFast'

   pinModeFast(_input_pin, INPUT);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp: In member function 'void PJON::send_bit(uint8_t, int)':

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:28: error: 'PORTD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:96:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, VALUE);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:73: error: 'PORTC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                                                                         ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:96:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, VALUE);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp: In member function 'void PJON::send_byte(uint8_t)':

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:28: error: 'PORTD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:118:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, HIGH);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:73: error: 'PORTC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                                                                         ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:118:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, HIGH);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:28: error: 'PORTD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:120:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, LOW);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:73: error: 'PORTC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                                                                         ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:120:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, LOW);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp: In member function 'int PJON::send_string(uint8_t, char*, uint8_t)':

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:92:28: error: 'DDRD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &DDRD : (((P) >= 8 && (P) <= 13) ? &DDRB : &DDRC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:144:88: note: in expansion of macro 'digitalPinToDDRReg'

 do {if (__builtin_constant_p(P) && __builtin_constant_p(V)) __atomicWrite__((uint8_t*) digitalPinToDDRReg(P),P,V) \

                                                                                        ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:149:3: note: in expansion of macro 'pinModeFast'

   pinModeFast(_input_pin, OUTPUT);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:92:71: error: 'DDRC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &DDRD : (((P) >= 8 && (P) <= 13) ? &DDRB : &DDRC))

                                                                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:144:88: note: in expansion of macro 'digitalPinToDDRReg'

 do {if (__builtin_constant_p(P) && __builtin_constant_p(V)) __atomicWrite__((uint8_t*) digitalPinToDDRReg(P),P,V) \

                                                                                        ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:149:3: note: in expansion of macro 'pinModeFast'

   pinModeFast(_input_pin, OUTPUT);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:28: error: 'PORTD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:162:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, LOW);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:73: error: 'PORTC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                                                                         ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:162:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, LOW);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp: In member function 'uint8_t PJON::syncronization_bit()':

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:94:28: error: 'PIND' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PIND : (((P) >= 8 && (P) <= 13) ? &PINB : &PINC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:9:33: note: in definition of macro 'BIT_READ'

 #define BIT_READ(value, bit) (((value) >> (bit)) & 0x01)

                                 ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:162:14: note: in expansion of macro 'digitalPinToPINReg'

  ( BIT_READ(*digitalPinToPINReg(P), __digitalPinToBit(P))) ) : \

              ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:159:37: note: in expansion of macro '_digitalReadFast_'

  #define digitalReadFast(P) ( (int) _digitalReadFast_((P)) )

                                     ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:270:23: note: in expansion of macro 'digitalReadFast'

   uint8_t bit_value = digitalReadFast(_input_pin);

                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:94:71: error: 'PINC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PIND : (((P) >= 8 && (P) <= 13) ? &PINB : &PINC))

                                                                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:9:33: note: in definition of macro 'BIT_READ'

 #define BIT_READ(value, bit) (((value) >> (bit)) & 0x01)

                                 ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:162:14: note: in expansion of macro 'digitalPinToPINReg'

  ( BIT_READ(*digitalPinToPINReg(P), __digitalPinToBit(P))) ) : \

              ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:159:37: note: in expansion of macro '_digitalReadFast_'

  #define digitalReadFast(P) ( (int) _digitalReadFast_((P)) )

                                     ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:270:23: note: in expansion of macro 'digitalReadFast'

   uint8_t bit_value = digitalReadFast(_input_pin);

                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp: In member function 'int PJON::receive_byte()':

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:92:28: error: 'DDRD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &DDRD : (((P) >= 8 && (P) <= 13) ? &DDRB : &DDRC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:144:88: note: in expansion of macro 'digitalPinToDDRReg'

 do {if (__builtin_constant_p(P) && __builtin_constant_p(V)) __atomicWrite__((uint8_t*) digitalPinToDDRReg(P),P,V) \

                                                                                        ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:292:3: note: in expansion of macro 'pinModeFast'

   pinModeFast(_input_pin, INPUT);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:92:71: error: 'DDRC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &DDRD : (((P) >= 8 && (P) <= 13) ? &DDRB : &DDRC))

                                                                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:144:88: note: in expansion of macro 'digitalPinToDDRReg'

 do {if (__builtin_constant_p(P) && __builtin_constant_p(V)) __atomicWrite__((uint8_t*) digitalPinToDDRReg(P),P,V) \

                                                                                        ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:292:3: note: in expansion of macro 'pinModeFast'

   pinModeFast(_input_pin, INPUT);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:28: error: 'PORTD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:293:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, LOW);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:73: error: 'PORTC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                                                                         ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:293:3: note: in expansion of macro 'digitalWriteFast'

   digitalWriteFast(_input_pin, LOW);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:94:28: error: 'PIND' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PIND : (((P) >= 8 && (P) <= 13) ? &PINB : &PINC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:9:33: note: in definition of macro 'BIT_READ'

 #define BIT_READ(value, bit) (((value) >> (bit)) & 0x01)

                                 ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:162:14: note: in expansion of macro 'digitalPinToPINReg'

  ( BIT_READ(*digitalPinToPINReg(P), __digitalPinToBit(P))) ) : \

              ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:159:37: note: in expansion of macro '_digitalReadFast_'

  #define digitalReadFast(P) ( (int) _digitalReadFast_((P)) )

                                     ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:295:10: note: in expansion of macro 'digitalReadFast'

   while (digitalReadFast(_input_pin) && micros() - time <= BIT_SPACER);

          ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:94:71: error: 'PINC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PIND : (((P) >= 8 && (P) <= 13) ? &PINB : &PINC))

                                                                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:9:33: note: in definition of macro 'BIT_READ'

 #define BIT_READ(value, bit) (((value) >> (bit)) & 0x01)

                                 ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:162:14: note: in expansion of macro 'digitalPinToPINReg'

  ( BIT_READ(*digitalPinToPINReg(P), __digitalPinToBit(P))) ) : \

              ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:159:37: note: in expansion of macro '_digitalReadFast_'

  #define digitalReadFast(P) ( (int) _digitalReadFast_((P)) )

                                     ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:295:10: note: in expansion of macro 'digitalReadFast'

   while (digitalReadFast(_input_pin) && micros() - time <= BIT_SPACER);

          ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp: In member function 'uint8_t PJON::read_byte()':

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:94:28: error: 'PIND' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PIND : (((P) >= 8 && (P) <= 13) ? &PINB : &PINC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:9:33: note: in definition of macro 'BIT_READ'

 #define BIT_READ(value, bit) (((value) >> (bit)) & 0x01)

                                 ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:162:14: note: in expansion of macro 'digitalPinToPINReg'

  ( BIT_READ(*digitalPinToPINReg(P), __digitalPinToBit(P))) ) : \

              ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:159:37: note: in expansion of macro '_digitalReadFast_'

  #define digitalReadFast(P) ( (int) _digitalReadFast_((P)) )

                                     ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:311:19: note: in expansion of macro 'digitalReadFast'

     byte_value += digitalReadFast(_input_pin) << i;

                   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:94:71: error: 'PINC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PIND : (((P) >= 8 && (P) <= 13) ? &PINB : &PINC))

                                                                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:9:33: note: in definition of macro 'BIT_READ'

 #define BIT_READ(value, bit) (((value) >> (bit)) & 0x01)

                                 ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:162:14: note: in expansion of macro 'digitalPinToPINReg'

  ( BIT_READ(*digitalPinToPINReg(P), __digitalPinToBit(P))) ) : \

              ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:159:37: note: in expansion of macro '_digitalReadFast_'

  #define digitalReadFast(P) ( (int) _digitalReadFast_((P)) )

                                     ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:311:19: note: in expansion of macro 'digitalReadFast'

     byte_value += digitalReadFast(_input_pin) << i;

                   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp: In member function 'int PJON::receive()':

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:92:28: error: 'DDRD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &DDRD : (((P) >= 8 && (P) <= 13) ? &DDRB : &DDRC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:144:88: note: in expansion of macro 'digitalPinToDDRReg'

 do {if (__builtin_constant_p(P) && __builtin_constant_p(V)) __atomicWrite__((uint8_t*) digitalPinToDDRReg(P),P,V) \

                                                                                        ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:340:3: note: in expansion of macro 'pinModeFast'

   pinModeFast(_input_pin, OUTPUT);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:92:71: error: 'DDRC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &DDRD : (((P) >= 8 && (P) <= 13) ? &DDRB : &DDRC))

                                                                       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:144:88: note: in expansion of macro 'digitalPinToDDRReg'

 do {if (__builtin_constant_p(P) && __builtin_constant_p(V)) __atomicWrite__((uint8_t*) digitalPinToDDRReg(P),P,V) \

                                                                                        ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:340:3: note: in expansion of macro 'pinModeFast'

   pinModeFast(_input_pin, OUTPUT);

   ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:28: error: 'PORTD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:345:7: note: in expansion of macro 'digitalWriteFast'

       digitalWriteFast(_input_pin, LOW);

       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:73: error: 'PORTC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                                                                         ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:345:7: note: in expansion of macro 'digitalWriteFast'

       digitalWriteFast(_input_pin, LOW);

       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:28: error: 'PORTD' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:351:7: note: in expansion of macro 'digitalWriteFast'

       digitalWriteFast(_input_pin, LOW);

       ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:90:73: error: 'PORTC' was not declared in this scope

 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))

                                                                         ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:125:12: note: in definition of macro '__atomicWrite__'

 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \

            ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\includes/digitalWriteFast.h:137:86: note: in expansion of macro 'digitalPinToPortReg'

 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \

                                                                                      ^

C:\Users\Jordan\Documents\Arduino\libraries\PJON\PJON.cpp:351:7: note: in expansion of macro 'digitalWriteFast'

       digitalWriteFast(_input_pin, LOW);

       ^

exit status 1
Error compiling.

</code>

**Comment by Earlz** [comment]
Er, don't use the version from the Arduino library service...

**Comment by gioblu** [comment]
What you mean! I didnt get this issue!
