### ISSUE TITLE
GlobalUDP strategy bus.reply does not work without bus.strategy.add_node

### ISSUE THREAD

**Issue by xlfe** [gioblu/PJON#230]
The docs for GlobalUDP say:

```
The IP address of the device can be DHCP assigned if none of the other devices need to reach it except with ACKs or replies. Otherwise it should be static.
```

I read this as I can use bus.reply without having to add the node using bus.strategy.add_node, but it doesn't work.

So, for example, if I have a "master" device at 192.168.0.10 and I have a number of slave nodes that have DHCP addresses, I some how have to add_node each slave before the master can send replies using bus.reply - this is less than ideal, especially since we are replying to a message from a know IP/bus_id.

On LINUX, I can get it to work as expected with the following patch:

```patch
diff --git a/src/interfaces/LINUX/UDPHelper_POSIX.h b/src/interfaces/LINUX/UDPHelper_POSIX.h
index b024c87..5b66fd4 100644
--- a/src/interfaces/LINUX/UDPHelper_POSIX.h
+++ b/src/interfaces/LINUX/UDPHelper_POSIX.h
@@ -165,6 +165,10 @@ public:
     send_string(string, length, _remote_receiver_addr);
   }

+  void send_string_reply(const uint8_t *string, uint16_t length) {
+      send_string(string, length, _remote_sender_addr);
+  }
+
   void set_magic_header(uint32_t magic_header) { _magic_header = magic_header; }
 };

diff --git a/src/strategies/GlobalUDP/GlobalUDP.h b/src/strategies/GlobalUDP/GlobalUDP.h
index 19cafbf..2c711b1 100644
--- a/src/strategies/GlobalUDP/GlobalUDP.h
+++ b/src/strategies/GlobalUDP/GlobalUDP.h
@@ -171,6 +171,9 @@ public:
           int16_t pos = find_remote_node(id);
           if (pos != -1) {
             udp.send_string(string, length, _remote_ip[pos], _remote_port[pos]);
+          } else {
+              // assume it is a bus.reply!
+              udp.send_string_reply(string, length);
           }
         }
       }
```

**Comment by fredilarsen** [comment]
Yes. There may be a possibility for letting incoming packets auto-register the sender in the node table, enabling reply() and also send(id) to that device after the first packet has been received.

A DHCP device that is rebooted and gets a new IP could have the node registration auto-update in the receiver when the first packet is received from the rebooted device. This makes it relatively dynamic.

Nice feature, should have added it in the first place. 

I will implement, test and push this. Hopefully there are no showstoppers in the Arduino network library, but it seems straight-forward.

@xlfe Have you looked at the broadcast based LocalUDP strategy, not needing any fixed IP addresses? (But limited to local network.)

**Comment by fredilarsen** [comment]
As an afterthought, letting DHCP based slaves send an empty registration packet to a master with fixed IP, at startup and perhaps every minute, will let the master talk to each slave by id without relating to IPs at all, giving capabilities nearly as simple as the LUDP strategy but bridging multiple Ethernet network segments.

Also, a PJON switch/router could be made to have this master role, and then connecting a lot of GUDP+DHCP based devices transparently with a SWBB or any other bus. Perhaps running a master with GUDP+DHCP as well, letting the switch be the only device with a fixed IP. Or no master, just devices talking to each other through the switch.

**Comment by xlfe** [comment]
Thanks @fredilarsen 

Your suggestions would definitely work for my use case!

Now I've solved my (silly) firewall issue, I've got a [Cython wrapper around PJON](https://github.com/xlfe/PJON-cython) working (very bare bones currently - but it works!) 

My end goal is to use a RaspberryPI as the "master" with application logic in Python (hence the need for a python wrapper) and have it connect to Wifi clients via GlobalUDP and wired clients via ThroughSerial to an Arduino (acting as a Bridge?) that then uses SWBB to route messages from the RPi master to other Arduino (like) devices.

**Comment by gioblu** [comment]
CIao @xlfe my compliments for [PJON-cython](https://github.com/xlfe/PJON-cython). I have added it in the list of the compliant tools. I am sure [PJON-cython](https://github.com/xlfe/PJON-cython) will be useful for many users! Feel free to contact us directly on gitter if you need support :)

Thank you again for your feedback.

**Comment by fredilarsen** [comment]
@xlfe I have just sent a pull request to @gioblu for the sender autoregistration in GUDP, just as described a few posts up. I have tested it on ESP8266 and Linux. It makes GUDP a lot more attractive in my case at least, and the ESP8266 a stronger candidate.

**Comment by xlfe** [comment]
The pull request looks good. Quick turnaround!

@fredilarsen that sounds like a pretty good demo - the new StdIO strategy would help open PJON to other languages (but I guess you'd still need to implement some of the bus ID details to encode/decode message destinations?)

One question - your ESP8266 GUDP-SWBB switch (or any switch) - can you use it as a node and a switch at the same time? 

For example, in my setup I'm would planning to have something like :

1) 1 master node running Linux (PJON-cython) with GUDP & ThroughSerial (two strategies) running
2) 1...n Wifi based ESP devices using GUDP (DHCP - so your pull request should be perfect)
3) 1x Arduino switch w/ ThroughSerial and SWBB connected to (1) and (4)
4) 1...n Arduinos w SWBB connected to (3)

What I'm not sure about is whether the switch (3) can act as a node in it's own right, as well as a switch?

**Comment by fredilarsen** [comment]
In the PJONAny constructor the default device id of a switch can be set. By default it is PJON_NOT_ASSIGNED (255) meaning the switch will be "invisible" on the bus.

If you assign an id to the switch, and use the PJONInteractiveSwitch which allows user callbacks for receive(forward) and error, you can implement your own logic. This is shown in BlinkingRGBSwitch.ino.
One thing to consider is that if your application logic use a lot of time it will reduce the efficiency of the switch as it gets reduced sample time for communication.

Regarding StdIO strategy you are right. For it to be usable the receiver id and sender id must be part of the simple messages. An alternative can be as space-separated text, with "44 46 " prefixing the real message.

Your setup seems fine. An alternative to the Arduino switch could be an ESP SWBB-LUDP switch in front of the Arduinos, getting rid of the serial wire and need to keep the switch close to a PC.

**Comment by xlfe** [comment]
Thanks @fredilarsen I will give it a go in the next few weeks and let you know if I have any problems.

thanks for all your assistance
