### ISSUE TITLE
PJONInteractiveRouter - allowing a switch or router to have it's own device id

### ISSUE THREAD

**Issue by andrei-volkau** [gioblu/PJON#236]
Class Description says that PJONInteractiveRouter allows a switch or router to have it's own device id. 
What should be done to assign the ID?

**Comment by gioblu** [comment]
Ciao @andrei-volkau sorry for the delay, see here: https://github.com/gioblu/PJON/issues/230#issuecomment-406857843

I will soon start to work on the router classes missing documentation :)

**Comment by andrei-volkau** [comment]
Hi @gioblu 
Thank you for the reference.
