### ISSUE TITLE
ThroughSerial can_start() returns false when no data received

### ISSUE THREAD

**Issue by xlfe** [gioblu/PJON#254]
Discovered this while adding testing to PJON-cython - 

in [strategies/ThroughSerial/ThroughSerial.h](https://github.com/gioblu/PJON/blob/master/src/strategies/ThroughSerial/ThroughSerial.h#L64) begin 

```C
    bool begin(uint8_t additional_randomness = 0) {
      PJON_DELAY(PJON_RANDOM(TS_INITIAL_DELAY) + additional_randomness);
      _last_byte = receive_byte();
      return true;
    };
```

`_last_reception_time` is not initialised - this appears to matter when can_start() is called later

suggest the following change

```diff
    bool begin(uint8_t additional_randomness = 0) {
      PJON_DELAY(PJON_RANDOM(TS_INITIAL_DELAY) + additional_randomness);
+     _last_reception_time = 0;
      _last_byte = receive_byte();
      return true;
    };
```

This way, initialisation of _last_reception_time is not dependent on receive_byte() being called and then PJON_SERIAL_AVAILABLE(serial) returning true.

**Comment by gioblu** [comment]
Ciao @xlfe thank you very much for reporting this.
