### ISSUE TITLE
LINUX Serial Support - serialDataAvailable() returns non-zero when ioctl returns an error even if no data is available for reading

### ISSUE THREAD

**Issue by xlfe** [gioblu/PJON#255]
I was getting some weird behaviour after adding tests to my PJON-cython ThroughSerial wrapper, and eventually tracked down the problem.

In [PJON_LINUX_Interface](https://github.com/gioblu/PJON/blob/master/src/interfaces/LINUX/PJON_LINUX_Interface.h#L154) serialDataAvailable does not initialise result - so if ioctl returns an error and does not set result, the function returns a non-zero number which indicates data is available for reading (when it is undetermined if data is available or not).

The following would fix it (plus a typo fix) :-

```diff
- /* Returns the number of bytes of data avalable to be read in the buffer */
+ /* Returns the number of bytes of data available to be read in the buffer */

  int serialDataAvailable(const int fd) {
-    int result;
+    int result = 0;
    ioctl(fd, FIONREAD, &result);
    return result;
  };
```

**Comment by gioblu** [comment]
Ciao @xlfe thank you very much 👍 
I have added the patch as suggested https://github.com/gioblu/PJON/commit/9e21f081c6045fadfcbb2c68813cd180169c6c73
