### ISSUE TITLE
bug: only #include "ESP32/ESPNOWHelper.h" if PJON_INCLUDE_EN is defined

### ISSUE THREAD

**Issue by xlfe** [gioblu/PJON#256]
Otherwise I'm getting a compilation error for PJON :(

PJON_Interfaces.h :-
```diff

#pragma once

#include "ARDUINO/PJON_ARDUINO_Interface.h"
#include "RPI/PJON_RPI_Interface.h"
#include "WINX86/PJON_WINX86_Interface.h"
#include "LINUX/PJON_LINUX_Interface.h"
+  #if defined(PJON_INCLUDE_EN)
    #include "ESP32/ESPNOWHelper.h"
+  #endif
```

**Comment by gioblu** [comment]
Ciao @xlfe is there any motivation why you did not include the helper in the `PJON_ARDUINO_Interface` (as the tcp or udp helpers of fred) considering that the helper depends on a custom arduino core?

**Comment by xlfe** [comment]
No that makes sense too actually. I guess the only reason not to is that it doesn't run on generic Arduino - but if you want to move it there I have no objections

**Comment by gioblu** [comment]
Another thing @xlfe why you include twice the helper both in `PJON_Interfaces` and in the Strategy itself?
Would not have sense to just remove the inclusion from the `PJON_Interfaces` file?

**Comment by gioblu** [comment]
@xlfe about custom core, the "norm" we have developed is just to fit in ARDUINO interface all arduino compatible cores see:  https://github.com/gioblu/PJON/blob/master/src/interfaces/ARDUINO/PJON_ARDUINO_Interface.h#L30

**Comment by xlfe** [comment]
Sounds sensible - no objections from me at all

**Comment by gioblu** [comment]
Consider that when compiling an ESPNOW sketch on ESP32, the interface used is ARDUINO, from where PJON takes all the basic system calls in the first place.

**Comment by xlfe** [comment]
true

**Comment by gioblu** [comment]
@xlfe it is a pleasure no probs, I am still reviewing your contribution, one thing I have noticed is that you include here: https://github.com/gioblu/PJON/blob/master/src/interfaces/ARDUINO/ESPNOWHelper.h#L3
and here: https://github.com/gioblu/PJON/blob/master/src/strategies/ESPNOW/ESPNOW.h#L24 `PJON` and `PJONDefines` files? Should they be already available for you there?

**Comment by xlfe** [comment]
> @xlfe it is a pleasure no probs, I am still reviewing your contribution, one thing I have noticed is that you include here: https://github.com/gioblu/PJON/blob/master/src/interfaces/ARDUINO/ESPNOWHelper.h#L3
> and here: https://github.com/gioblu/PJON/blob/master/src/strategies/ESPNOW/ESPNOW.h#L24 `PJON` and `PJONDefines` files? Shouldnt they be already available for you there?

Yes - removing the include from ESPNOW.h doesn't cause any problems

**Comment by gioblu** [comment]
Good @xlfe thank you again for testing it, I will remove those :)
