### ISSUE TITLE
delete is undefined for new[], use delete[] instead

### ISSUE THREAD

**Issue by xlfe** [gioblu/PJON#262]
https://github.com/gioblu/PJON/blob/87f4649a206a55c32e4dd27f66efe2dc4d8c339e/src/interfaces/LINUX/UDPHelper_POSIX.h#L135

memory was allocated using new[], should be deleted using delete[], not delete

**Comment by gioblu** [comment]
Ciao @xlfe thank you very much for your support :)
I will fix this as soon as possible.

**Comment by gioblu** [comment]
Ciao @xlfe fixed, thank you very much :)
