### ISSUE TITLE
Why does ThroughSerial (and Async) send_string only support a maximum length of 255?

### ISSUE THREAD

**Issue by xlfe** [gioblu/PJON#264]
https://github.com/gioblu/PJON/blob/6fcfd759c6f376bd1328a681bd644790fea021b2/src/strategies/ThroughSerial/ThroughSerial.h#L181

https://github.com/gioblu/PJON/blob/6fcfd759c6f376bd1328a681bd644790fea021b2/src/strategies/ThroughSerialAsync/ThroughSerialAsync.h#L277

Shouldn't these functions support a length > 255 ?

**Comment by gioblu** [comment]
Ciao @xlfe thank you for your support 👍 
The TS and TSA strategies support up to 255 bytes because in most use cases the buffer is smaller than 255 bytes, but yes, I agree with you it has sense to support length > 255 as other strategies do.
I will soon make the change and relate it to this issue.

**Comment by gioblu** [comment]
CIao @xlfe fixed, thank you for the report.
