### ISSUE TITLE
There is no encryption (or however it was the word was misspelled!)

### ISSUE THREAD

**Issue by jayeye** [gioblu/PJON#31]
Why claim you have encryption when you don't? Also, crypto should not be done at this layer in the first place.

**Comment by gioblu** [comment]
@jayeye Ciao again, true, encryption should not be at this level and that are remains of an older version comments (pre 1.0) where Cape library was still not extracted from the PJON codebase.

Comment update soon

**Comment by gioblu** [comment]
@jayeye thank you again for your support.
