### ISSUE TITLE
Support for Attiny402

### ISSUE THREAD

**Issue by kopierreko** [gioblu/PJON#346]
Is it possible to support Attiny402 ?

**Comment by gioblu** [comment]
CIao @kopierreko it may work although you would not have much memory left for the program.

**Comment by kopierreko** [comment]
It's what I encountered when I tried to modify the sources... I was searching for a solution to make a one wire slave with attiny402 and I found your projet which look really nice but there is this problem of memory now ^^
Thanks 😊

**Comment by gioblu** [comment]
Ciao @kopierreko the smaller MCU PJON supports is ATtiny85, that is already a feat, I am not sure we will ever be able to support the 4k family. You may have luck using the SoftwareBitBang strategy alone, and design for it, a custom, simpler, packet format.
