### ISSUE TITLE
AT commands on HC-11

### ISSUE THREAD

**Issue by rwlakin** [gioblu/PJON#348]
No AT response using TeraTerm virtual terminal.  Works fine on all bluetooth modules. Trying several HC-11 modules.  Pin 5 to gnd.

**Comment by gioblu** [comment]
Ciao @rwlakin I have recently bought Reyax LoRa modules to implement AT commands support. For now PJON using ThroughSerial or ThroughSerialAsync can work with HC-12 and other "transparent" modules. 

>  Works fine on all bluetooth modules
I have never tried bluetooth modules, would you tell me the models so I can list them in the documentation? Have you used ThroughSerial or ThroughSerialAsync?

Thank you for your support.

**Comment by rwlakin** [comment]
Problem solved.  I stop using TeraTerm and switch to CoolTerm and it works
fine.  Haven't tried the ESP8655 module yet.
