### ISSUE TITLE
bus.reply fail to send before ESP.restart();

### ISSUE THREAD

**Issue by fotosettore** [gioblu/PJON#349]
hi Giovanni
i need to restart a slave when requested from master.
And before restart, I send to master a message that slave is resetting itself.
I use this simple code :
```
...
bus.reply("RESET"), 5);
delay (2000);
ESP.restart();
```
but it does not work.
I tried to use a "millis" routine but it does not work too.
I tried to comment ESP.restart() and the message is send succesfully.

Any idea to solve?

ciao

**Comment by gioblu** [comment]
Ciao @fotosettore I think the problem is you don't call `update` after `reply`, so the packet is dispatched in the buffer but never transmitted.

**Comment by fotosettore** [comment]
i'm sorry
it does not work :-(
`...
bus.reply("RESET"), 5);
bus.update();
delay (2000);
ESP.restart();`

any more idea ?

**Comment by gioblu** [comment]
Ciao @fotosettore `update` returns the number of packets that are still to be transmitted, when its return value is 0 means all packets dispatched were transmitted. Instead of calling a `delay` try to call update until it returns 0, it should fine then.

**Comment by fotosettore** [comment]
Well done Giovanni !
Many thanks for your input !
Now, using this code, all works fine
```
          unsigned long LastResetTime = millis();
          while ( bus.update() != 0 )
          {
              if (millis() - LastResetTime > 2000)
              {
                 break;
              }
          }
         
          ESP.restart();
```
I also used **millis** to force exit if any problem about communication happen.
Ciao
Peppe

**Comment by gioblu** [comment]
Ciao @fotosettore thank you, consider that when the maximum amount of retries is reached the packet is discarded, so `update` will return 0, no risk of looping in there forever :)

**Comment by fotosettore** [comment]
so ... how many maximum amount of retries are allowed ?

**Comment by gioblu** [comment]
Ciao @fotosettore if using SoftwareBitBang it takes around 3.5 seconds and 20 retries.
