### ISSUE TITLE
Timing in a separate file

### ISSUE THREAD

**Issue by gioblu** [gioblu/PJON#36]
Ciao! I am considering to move timing values in a new file `Timing.h` to have a dedicated space for that and to mantain clarity and add practical space for useful comments. Let me know what you think about it.

**Comment by aperepel** [comment]
I'm  in support of making things more accessible. This might help. E.g. if one is thinking of writing a custom parser for a logic analyzer capture,  having all possible timings easily accessible helps. Today it's  somewhat buried in main files.

**Comment by gioblu** [comment]
@aperepel right, buried is the right word.
I would make this modification after the release (soon) of 1.2 with ESP and Zero compatibility. We are working to test it extensively because its quite a huge update. After all this process I will start with this issue on the next release (1.3).

**Comment by gioblu** [comment]
@aperepel I close this issue because has been fixed in 2.0
