### ISSUE TITLE
Topology - SoftwareBitBang

### ISSUE THREAD

**Issue by happen-studio** [gioblu/PJON#400]
Hi, 

I'm planning to use PJON (SoftwareBitBang) in my house, right now I'm designing some custom PCBs. 
I had a look in the docs, but I can't find any information about the wiring, what is possible what not? 

See attached a random groundplan with a couple of ESP32/custom PCB and a master (raspberrypi) to get a better picture of my question. Is this wiring possible, are there any limitations (star topology, linear topology, …) ?

The other two pictures showing a frontal perspective, with two versions of wiring. 

thanks a lot.

<img width="1013" alt="groundplan-topology" src="https://user-images.githubusercontent.com/79902414/144833860-1a4f71e6-bc74-4c2e-955c-149614a60706.png">
<img width="703" alt="a" src="https://user-images.githubusercontent.com/79902414/144834776-89470824-f9c3-4319-b86f-90e3ce52e453.png">
<img width="698" alt="b" src="https://user-images.githubusercontent.com/79902414/144834781-e706b1e0-79b4-4f2f-9007-e5343e5bb59a.png">

**Comment by gioblu** [comment]
Ciao @happen-studio you can just use a single wire connecting all devices. The topology can be bus or star.
Check out the SWBB documentation here: https://github.com/gioblu/PJON/tree/master/src/strategies/SoftwareBitBang#softwarebitbang
Check out also:
https://github.com/gioblu/PJON/wiki/Protective-circuitry
https://github.com/gioblu/PJON/wiki/Mitigate-interference
https://github.com/gioblu/PJON/wiki/SoftwareBitBang-cabling-and-connectors

**Comment by happen-studio** [comment]
Hi @gioblu,
thank you very much for the input, did't find the points in the wiki. ;-)
The posted groundplan is a mixture of bus and star. Is it possible to mix both topologies?

@gioblu thanks a lot for all the work with PJON.

**Comment by gioblu** [comment]
Yes you can mix topologies :)
It is a pleasure :)
