### ISSUE TITLE
ESP <-> Mega - is level shifter supported ?

### ISSUE THREAD

**Issue by furynick** [gioblu/PJON#414]
I'm trying to establish a communication between an ESP8266 and a Mega with SBB, I'm using a bidirectionnal level shifter as shown below but it seems it's not working.

Is it possible ?
Which type of shifter should I use ?

![image](https://user-images.githubusercontent.com/3520080/162589641-48a5863c-5482-4e92-976e-a283048a2e1d.png)

**Comment by furynick** [comment]
Found [solution in Wiki](https://github.com/gioblu/PJON/wiki/ESP8266-interfacing).

Tested  just now and working.

**Comment by gioblu** [comment]
Ciao @furynick have you implemented the alastair's "converter"?

**Comment by furynick** [comment]
Yes I do and it's working, thanks.
