### ISSUE TITLE
Refactoring digitalFastWrite.h include to be a sibling

### ISSUE THREAD

**Issue by aperepel** [gioblu/PJON#49]
Hi, can we move the subj to be on the same level as all other header files? E.g. it makes things work out of the box when not using an arduino ide, otherwise have to go in and modify the paths manually.

**Comment by gioblu** [comment]
You would remove includes directory?

**Comment by aperepel** [comment]
Yes, it always caused issues when building from command line. E.g. with PlatformIO, the library becomes available on a system path via <> style includes. Using directory paths in "" doesn't work well with this structure.

**Comment by gioblu** [comment]
Ciao @aperepel I am a little captured by some issues, could you please propose a fix to this?
Or in any case I will come back to this point as soon as possible.
Thank you again.

**Comment by gioblu** [comment]
To be fixed in 2.0 stable

**Comment by gioblu** [comment]
@aperepel fixed.
Now should be more easy to be used on platformio.
