### ISSUE TITLE
Use of interrupts? 

### ISSUE THREAD

**Issue by sticilface** [gioblu/PJON#54]
I completely understand your desire to implement this entirely in software.  This is more of a theory question.  I have not tried to implement it yet as I've not got pjon working on ESP8266 just yet!  but here goes.. 

The ESP8266 wifi has to be serviced every so often, otherwise you get a crash.  polling a pin for 1ms constantly is not the 'most' efficient thing to do, and would hold up wifi.  Is there any reason why I can't put the 
```
network.receive(1000);
```
receive function inside a call back, and say set the timeout to 1?  Would this in theory still work? 

This lib looks wicked!  and works very well on arduino so thumbs up.

cheers

A

**Comment by gioblu** [comment]
Ciao @sticilface !
I don't see any limit using PJON inside a interrupt callback, if you can give it a try!
Thank you for compliments, if you like spread the voice :+1: !
