### ISSUE TITLE
Update does not try to send if package in index 0 is done

### ISSUE THREAD

**Issue by shacal** [gioblu/PJON#77]
I  think row 2 in update() function should be swapped from https://github.com/gioblu/PJON/blob/master/PJON.h#L536
> 536: if(packets[i].state == 0) return;

to

> 536: if(packets[i].state == 0) continue;

This keeps update sending other packages in every loop.

**Comment by gioblu** [comment]
Ciao @shacal absolutely right.
You found a bug, thank you for your report.

**Comment by gioblu** [comment]
Bus fixed, I will mention your report in the next release.
Thank you again and have fun with PJON.
